[package]
name = "mta"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
curv-kzen = "0.10.0"
paillier = "0.2.0"
k256 = "0.13.3"
secp256k1 = "0.28.2"
num = "0.4.1"
serde = "1.0.197"
sha2 = "0.10.8"